name: Package ilivalidator

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version?'
        required: true

jobs:  
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-10.15', 'windows-latest']
        include:
          - os: 'ubuntu-20.04'
            label: 'linux'
            package: 'deb'
            icon: 'icons/icon-ilivalidator-128x128.png'
            asset_prefix: 'ilivalidator_'
            asset_suffix: '-1_amd64'
          - os: 'macos-10.15'
            label: 'mac'
            package: 'pkg'
            icon: 'icons/icon-ilivalidator-128x128.icns'
            asset_prefix: 'ilivalidator-'
            asset_suffix: ''
          - os: 'windows-latest'
            label: 'win'
            package: 'msi'
            icon: 'icons/icon-ilivalidator-128x128.ico'
            asset_prefix: 'ilivalidator-'
            asset_suffix: ''
    runs-on: ${{matrix.os}}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'Download zipped ilivalidator release'
        run: |
          curl -L https://downloads.interlis.ch/ilivalidator/ilivalidator-${{ github.event.inputs.version }}.zip -o ilivalidator.zip
      - name: 'Unzip ilivalidator release'
        run: |
          unzip ilivalidator.zip
      - name: 'Setup Java 16'
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: 'Get dependencies (jdeps)'
        run: |
          echo "DEPS=$(jdeps --class-path 'libs/*' --multi-release base -recursive --ignore-missing-deps --print-module-deps ilivalidator-${{ github.event.inputs.version }}.jar)" >> $GITHUB_ENV
        shell: bash
      - name: 'Create JRE (jlink)'
        run: |
          jlink --add-modules ${{env.DEPS}} --output ilivalidator-jre
      - name: 'Copy main jar to libs'
        run: |
          cp ilivalidator-${{ github.event.inputs.version }}.jar libs/
      - name: 'Create package (jpackage)'
        run: |
          jpackage --icon ${{matrix.icon}} --name ilivalidator --type ${{matrix.package}} --input libs --main-jar ilivalidator-${{ github.event.inputs.version }}.jar -d output --runtime-image ilivalidator-jre --app-version ${{ github.event.inputs.version }} --java-options -Xmx2g 
        shell: bash
      - name: List all files in output directory
        run: ls -la output
        shell: bash
      - name: List all files in project root directory
        run: ls -la 
        shell: bash
      - name: 'Setup Java 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Upload file to bucket
        shell: bash
        run: |
          ./gradlew uploadFile 
        env:
          FILENAME: ${{matrix.asset_prefix}}${{ github.event.inputs.version }}${{matrix.asset_suffix}}.${{matrix.package}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1"
